/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kpop

import io.ktor.application.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.features.*
import io.ktor.serialization.*

import kpop.models.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    install(CORS) {
        anyHost()
    }
    install(ContentNegotiation) {
        json()
    }
    routing {
        get("/") {
            call.respondText("Hello, world!")
        }
        get("/json") {
            call.respond(Message(message="hi !"))
        }
    }
}
